apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-test2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test2
  template:
    metadata:
      labels:
        app: nginx-test2
    spec:
      containers:
      - name: nginx-test2
        image: nginx:1.24
        ports:
        - name: http
          containerPort: 80
